#QUERY <http://fbwsvcdev.fh-brandenburg.de:8080/fuseki/EduGraph/query>

PREFIX schema: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bise:  <http://akwi.de/ns/bise#>
PREFIX dbpedia-de: <http://de.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>


CONSTRUCT {
	?universityURI a schema:CollegeOrUniversity
}
WHERE {
	{
		
		SELECT * 
		WHERE{
		{
			SELECT ?universityURI (COUNT(?universityLocationURIs) AS ?num)  WHERE {
				GRAPH <http://fbwsvcdev.fh-brandenburg.de:8080/fuseki/EduGraph/data/akwiUniversitities> {
				{ 
					SELECT * WHERE {
						?universityURI  a schema:CollegeOrUniversity
					}
				}
				}

			    	SERVICE <http://de.dbpedia.org/sparql/> {
						?universityURI dbpedia-owl:locationCity ?universityLocationURIs;
			    	}

			}
			GROUP BY ?universityURI
		} 
		FILTER(?num < 2)
		}
		
	
	}

}


